from .communication_guardrails import (
    KNOWLEDGE_BOUNDARY_GUARDRAIL,
    SKINCARE_COMPLIANCE_GUARDRAIL,
    COLLABORATOR_INTEREST_GUARDRAIL
)
from .system_guardrails import (
    ROUTING_CONTEXT_GUARDRAIL,
    SOURCE_ATTRIBUTION_GUARDRAIL,
    RETENTION_AND_LIFECYCLE_GUARDRAIL
)

GLOBAL_GUARDRAILS = f"""
--- MANDATORY SYSTEM GUARDRAILS ---
{KNOWLEDGE_BOUNDARY_GUARDRAIL}
{SKINCARE_COMPLIANCE_GUARDRAIL}
{COLLABORATOR_INTEREST_GUARDRAIL}
{ROUTING_CONTEXT_GUARDRAIL}
{SOURCE_ATTRIBUTION_GUARDRAIL}
{RETENTION_AND_LIFECYCLE_GUARDRAIL}
"""
